language: python
python:
- 3.6
sudo: required
services:
- docker
before_script:
- pip install requests
- pip install codecov
- pip install pytest pytest-cov
env:
- CODECOV_TOKEN="56acb56f-bfd0-485a-b0bd-158c6808bf41"
script:
- docker-compose up -d web
- docker-compose ps
- pytest --cov=./
deploy:
  provider: heroku
  api_key:
    secure: ixMrjasgRLezBoU5ESihB9zjysUe3JRfq5UlE83C4e+Dlj6xySgeI7iYFwr5SO5m+LxqrMXb5EAw2JORFZVZdx/XxXe3KmgX/4uDimuSxJ4ASrn+aYijGhAGFtOjUfbZdjQa70epb+O+0Y7RprtA4oBhP3dc3+j2D1JXhFqihybV7GYnB3y3K+2YxVd8jMuLi/pqRO88SieNWaeyQNBgiIFuhIN54UaV2z+z9UqmUROBtaj+V1RhtfRCyfMRrHjaTeyHOMw5tco8EyikZ7q984RgtEGU4U+VT7aS52vNXivtbN7ppO8rYdnI03kgYv2J5U6D5kLiNFOEik8PXAdNPSghi22wBQ9d7jdWxk7jZmTOnTWVoJ4FcIM4M1kvBp0ykO01JRyOpiMcZbiKzeGRt8M3xqolL5bgOyFghYNRUb2X/ZYGLgP5oOruVH/8Kig0jjJHW9xEscpTK8Mh0/CvQHb7xVynBTgSb9FwE4AcoUQAfGbCcngkI5bER/KhhkK0WJBKid6AeAuFgAgTzaDsPOcqmoOqvH1qOn0WzTBBGc5q1QgtHAPsHD5NU7SwsaDpyGt0ElfIKL88xpeDlVl/choMf2Csjml4Zn3Rn6Pv1OK19qXE5TKM9WYKVIOyzxTm9lLOG3ZxQR9mBuPvXyjNyBILG4bx9PDkEO2HzEuwW74=
