language: python
python:
- 3.6
sudo: required
services:
- docker
before_script:
- pip install requests
- pip install codecov
- pip install pytest pytest-cov
env:
- CODECOV_TOKEN="56acb56f-bfd0-485a-b0bd-158c6808bf41"
script:
- docker-compose up -d web
- docker-compose ps
- pytest --cov=./
deploy:
  provider: heroku
  api_key:
    secure: EfKmbgO7FHM30d9OTROo0NwUGNxRb27euQ8UhB2kp2zdEhNq6R/QXAWfyQQSt+xq3UpQqlCPamyu/W/BA7/DM8rpuw9kd00kRWLrnxvDMpoia4/g3EwoLlf+KHDMEM3rBKiawpMaek1QCyQmMCpoUou8Yh3Cugn7dUeLPAxn2JoPdTf24x1bLGLHKAqwSXLuK8EV6RWNkO73Uf5iALajQQCe5mHvseFsQanbsZwjNUFmGtYztqZh3eoY611lrrohwTvLS5OfF667PlS+wBQhkQIVkdXogfb5eXsx5/ypga0Y87RZb4dDcwtxOVUAeGf6p1Ndyu24+n9IBeewWH6JC+FMK1l6juieY+CRc+qde3jeio1Zs1BJr5gW38KDPACajwTMkMUPQrYJxGv+sIK7zb1L2E2RdbGT2URYO+co8FsqUlufT8pMeXm5NEh28w6mINWrnTVILpMoNC7Y8qo0b42YS1Ggue248sup+xVvVi9Ftw3mdd9kCGxrccb4bHqv1XwP+BkDI6AtKpcLmDrLeFd3moZgdPtaRaiG+al6O7BJUAynJtjGD6qLIt0i+wFIgSHX7i55WXbEHBp24dlEl+1PLuUApmrxKypEo5nWVqQrmE7ge6LPIwPc2Uck5RKxW/tV47aCqX+fvMOVSJrYZA5htS4XsJC23hxBl480cw4=
