version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
    network_mode: "host"
    command: >
      bash -c "flask run --port=5000"
    # Infinite loop, to keep it alive, for debugging
    # command: /bin/ash -c "while true; do echo 'sleeping...' && sleep 10; done"
